#!/usr/bin/env php
<?php
require_once '/var/www/vendor/autoload.php';
require_once 'donne/crusharray.php';

$dbname = getenv('MYSQL_DATABASE');
$dbuser = getenv('MYSQL_USER');
$dbpassword = getenv('MYSQL_PASSWORD');
$dbcontainer = getenv('CONTAINER_MYSQL');

$pdo = new PDO("mysql:host=$dbcontainer;dbname=$dbname", $dbuser, $dbpassword);

//creation table
echo "[";
$etape = $pdo->exec("CREATE TABLE user(
            id INT UNSIGNED NOT NULL AUTO_INCREMENT,
            name VARCHAR(255) NOT NULL,
            password VARCHAR(255) NOT NULL,
            PRIMARY KEY(id)
            )");
"||";

$etape = $pdo->exec("CREATE TABLE `user_infos`(
            `id_user` INT(11) NOT NULL AUTO_INCREMENT,
            `name` VARCHAR(255) NOT NULL,
            `email` VARCHAR(255) NOT NULL,
            `password` VARCHAR(255) NOT NULL,
            `token` VARCHAR(255) NOT NULL,
            `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
            PRIMARY KEY(id_user)
            )");
"||]";

$pdo->exec("CREATE TABLE `crush`(
        `id` INT(11) NOT NULL AUTO_INCREMENT,
        `nom` VARCHAR(255) NOT NULL,
        `img` TEXT NOT NULL,
        PRIMARY KEY(id)

)");
"||";

//vidage table
$pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
$pdo->exec('TRUNCATE TABLE user');
$pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

/*$pdo->exec("INSERT INTO status (`label`) VALUES 
  ('En attente de paiement'),
  ('En cours de préparation'),
  ('Expédiée'),
  ('Terminée')");*/

$password = password_hash('admin', PASSWORD_BCRYPT);

$pdo->exec(
        "INSERT INTO `user` SET
        `name`='admin',
        `password`='{$password}'
        ");
echo "||";


$pdo->exec(
  "INSERT INTO `crush` (`id`, `nom`, `img`) VALUES
  (1, 'Castiel', 'http://ekladata.com/L6QSAEYigCO1yRPz6uEm-HzfAuE.png'),
  (2, 'Lysandre', 'http://static1.wikia.nocookie.net/__cb20130331071426/amordoce/images/1/11/LysandreE3.png'),
  (3, 'Armin', 'http://ekladata.com/mcGwusXYnbSpTAElgJEmteLJNZg.png')
  ");
echo "||";


echo "||";

echo "||||]".PHP_EOL;
//}